server:
  port: 8090
  servlet:
    context-path: /

spring:
  application:
    # 应用名称
    name: Crawler

  # 因为Springfox使用的路径匹配是基于AntPathMatcher的，而Spring Boot 2.6.X使用的是PathPatternMatcher
  # 所以需要统一一下path matcher规则
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # 数据库配置
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:p6spy:mysql://localhost:3306/crawler?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

    # Druid配置
    # 初始化连接数量
    druid:
      db-type: mysql
      initial-size: 1
      # 最小空闲连接数
      min-idle: 1
      # 最大并发连接数
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 是否开启PSCache，如果用Oracle，则把poolPreparedStatements配置为true，mysql可以配置为false
      pool-prepared-statements: false
      max-open-prepared-statements: 20
      # 每个连接上PSCache的大小
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的Filter，去掉后监控界面SQL无法统计，wall用于防火墙
      filters: stat,wall
      # filters: stat,wall,log4j
      # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
#      aop-patterns: com.springboot.servie.*
      # 打开removeAbandoned功能(连接泄漏监测，怀疑存在泄漏之后再打开)
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      # 关闭abandoned连接时输出错误日志
      log-abandoned: true
      # 通过 connection-properties 属性打开 mergeSql 功能；慢 SQL 记录
      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000

      # WebStatFilter配置
      web-stat-filter:
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*

      # StatViewServlet配置
      stat-view-servlet:
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # IP 白名单，没有配置或者为空，则允许所有访问
        allow: 127.0.0.1
        # IP 黑名单，若白名单也存在，则优先使用
        deny: 192.168.1.218
        # 禁用 HTML 中 Reset All 按钮，是否能够重置数据
        reset-enable: false
        # 登录用户名/密码
        login-username: druid
        login-password: druid

      # 配置StatFilter
      filter:
        stat:
          log-slow-sql: true


logging:
  config: classpath:logback-spring.xml
  file:
    path: ./log #只可以只当log的路径, 不能指定log的名字, 使用缺省值spring.log
    # 需要配置log文件才可以在Spring Boot Admin 监测页面上查看的客户端应用日志。
#    name: ./log/boot.log #可以指定路径和log文件的名字
#  pattern:
#    console: '%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'
#    file: '%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'
#  level:
#    root: info #指定根日志记录级别, 即全局
#    com.bear.springboottest: debug #指定包日志记录级别
debug: false #输出更多装配信息, 但是日志不会被设为debug level